[package]
name = "astcenc-rs"
version = "0.1.0"
authors = ["Jef <jackefransham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astcenc-sys = { path = "../astcenc-sys/" }
bitflags = "1.2"
half = "1.6"
